services:
  pg:
    image: "postgres:15.2-alpine"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pissword
      POSTGRES_DB: group3db
    ports:
      - "5432:5432"
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "pg:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5433:80"
    depends_on:
      - pg
  web:
    build: .
    env_file:
      - .env
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - pg_proxy